inherit_gem:
  rubocop-espago: rubocop.yml

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - lib/tapioca/**/*.rb

Style/DocumentationMethod:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
